---
- name: My playbook
  hosts: all
  tasks:
    - name: Leaving a mark
      command: "touch /tmp/ansible_was_here"
    - name: Check if we were here
      command: "test -f /tmp/ansible_was_here"
      register: result
      changed_when: false
      failed_when: false
      ignore_errors: true
      delegate_to: localhost
